---
name: Number-Ops
version: 1.02
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: Simple operations on numbers.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Number::Ops:
    file: lib/Number/Ops.pm
    version: 1.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
